services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_BASE_URL: http://localhost:3000
        VITE_USER_BASE_URL: http://localhost:3001
        VITE_CAPTAIN_BASE_URL: http://localhost:3002
        VITE_GOMAPS_PRO_API_KEY: AlzaSyYyWisdp7rqpRhBwcpcvm5Dxg21UKZpZjC
        VITE_RAZORPAY_KEY_ID: rzp_test_bKWKJEeA520i0h
        VITE_RAZORPAY_KEY_SECRET: xjAp9h1tGHQmCz1bk5Kdqwtq
    ports:
      - "5000:80"
    depends_on:
      - gateway
    env_file:
      - ./env/frontend.env
    restart: always
    networks:
      - microservice_network

  gateway:
    build:
      context: ./Backend/gateway
    ports:
      - "3000:3000"
    depends_on:
      - user
      - ride
      - captain
      - payment
      - dynamic_price
      - maps
    env_file:
      - ./env/gateway.env
    restart: always
    networks:
      - microservice_network

  user:
    build:
      context: ./Backend/user
    ports:
      - "3001:3001"
    env_file:
      - ./env/user.env
    restart: always
    networks:
      - microservice_network

  captain:
    build:
      context: ./Backend/captain
    ports:
      - "3002:3002"
    env_file:
      - ./env/captain.env
    restart: always
    networks:
      - microservice_network

  ride:
    build:
      context: ./Backend/ride
    ports:
      - "3003:3003"
    env_file:
      - ./env/ride.env
    restart: always
    networks:
      - microservice_network

  maps:
    build:
      context: ./Backend/maps
    ports:
      - "3004:3004"
    env_file:
      - ./env/map.env
    restart: always
    networks:
      - microservice_network

  payment:
    build:
      context: ./Backend/payment
    ports:
      - "3006:3006"
    env_file:
      - ./env/payment.env
    restart: always
    networks:
      - microservice_network

  dynamic_price:
    build:
      context: ./Backend/dynamic_price
    ports:
      - "3005:3005"
    env_file:
      - ./env/dynamic_price.env
    restart: always
    networks:
      - microservice_network

networks:
  microservice_network:
    driver: bridge
