---
# ✅ NodePort Services
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: captain-service
spec:
  selector:
    app: captain
  type: NodePort
  ports:
    - port: 3002
      targetPort: 3002
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: ride-service
spec:
  selector:
    app: ride
  type: NodePort
  ports:
    - port: 3003
      targetPort: 3003
      nodePort: 30003
---
apiVersion: v1
kind: Service
metadata:
  name: maps-service
spec:
  selector:
    app: maps
  type: NodePort
  ports:
    - port: 3004
      targetPort: 3004
      nodePort: 30004
---
apiVersion: v1
kind: Service
metadata:
  name: dynamic-price-service
spec:
  selector:
    app: dynamic-price
  type: NodePort
  ports:
    - port: 3005
      targetPort: 3005
      nodePort: 30005
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  type: NodePort
  ports:
    - port: 3006
      targetPort: 3006
      nodePort: 30006
